title: "XI ERAD/SE 2026"
description: "Escola Regional de Alto Desempenho da Região Sudeste"
baseurl: "/erad-se2026"
url: "https://crad-se.github.io"

remote_theme: pages-themes/cayman@v0.2.0

show_downloads: false

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

# Dados do evento
event:
  edicao: "XI"
  nome_completo: "Escola Regional de Alto Desempenho da Região Sudeste"
  sigla: "XI ERAD/SE 2026"
  local: "Juiz de Fora – MG"
  instituicao: "Universidade Federal de Juiz de Fora (UFJF)"
  datas: "12 a 14 de Agosto de 2026"

# SEO
author: "CRAD/SE"
twitter:
  username: eradse
lang: pt-BR

email: 

